services:
  mongodb:
    image: mongo:8
    container_name: hotel-management-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  mailpit:
    image: axllent/mailpit:latest
    container_name: hotel-management-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mongodb_data:
